# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: digging_arm
  joint_model_group_pose: move_to_dig
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - base_to_digging_link_1
    - digging_link_1_to_2
    - digging_link_2_to_3
    - base_to_seeding_link_1
    - seeding_link_1_to_2
    - seeding_link_2_to_3
    - seeding_link_to_clamp1
    - seeding_link_to_clamp2
    - base_to_tyre1
    - base_to_tyre2
    - base_to_tyre3
    - base_to_tyre4
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
seeding_arm_controller:
  type: position_controllers/JointPositionController
  joints:
    - base_to_seeding_link_1
    - seeding_link_1_to_2
    - seeding_link_2_to_3
  gains:
    base_to_seeding_link_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    seeding_link_1_to_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    seeding_link_2_to_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
digging_arm_controller:
  type: position_controllers/JointPositionController
  joints:
    - base_to_digging_link_1
    - digging_link_1_to_2
    - digging_link_2_to_3
  gains:
    base_to_digging_link_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    digging_link_1_to_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    digging_link_2_to_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1